### PR TITLE
Added ini settings choice for strict portability

### PR DESCRIPTION
**Pull request by bdeshi**
_Mainly for inclusion in portable releases of AutoHotkey with AHK2Exe._

Set `useIni=1` in `AHK2Exe.ini`, and settings that would would be saved registry are now saved in this ini file instead.

Since AHK2Exe is bundled with the _portable_ package of AHK too, its unrestricted registry modification goes against the idea of portability.
If this PR is accepted, @Lexikos can simply toggle `useIni` accordingly for the portable and installer-based releases.

&nbsp;

The ini file should remain in UTF-16LE encoding. ~~UTF-8 also works, but apparently not always - special characters can get converted to ?-mark. Besides, UTF-16 is the default for Ini- operations of AHK.~~
_Github's webbased diff page shows it as binary but its displayed normally elsewhere._

### CODE REVIEW

**Comment by Lexikos** [comment]
Is there any reason that the INI file should be included at all in the installer-based release?

> UTF-8 also works

FYI, the Windows INI functions are strictly ANSI or UTF-16 only.  They do not support UTF-8, but in some limited cases the data will come through without corruption.  For instance, GetPrivateProfileStringA will return the data as-is, because the data is expected to be 8-bit ANSI, and that's what the function is supposed to return.  IniRead uses this function in ANSI builds of AutoHotkey.  In Unicode builds, it uses GetPrivateProfileStringW, which will reinterpret the data as ANSI text and attempt to convert it to UTF-16.

**Comment by smsrkr** [comment]
> Is there any reason that the INI file should be included at all in the installer-based release?
No, defaults to registry in absence of the ini.

**Comment by joedf** [comment]
> Is there any reason that the INI file should be included at all in the installer-based release?
  
What about the installer? He wants the INI file `ahk2exe.ini` to be only included in the portable releases. Eg. The `.zip` releases.

**Comment by smsrkr** [comment]
> What about the installer? He wants the INI file ahk2exe.ini to be only included in the portable releases. Eg. The .zip releases.

Yes, that's what I said. The ini can be safely skipped from the installer; AHK2Exe will use the registry as usual then. :)

**Comment by joedf** [comment]
This is now superseded by the use of ahk-directives. The "Save Script Settings As ..." option can also be used.

**Pull request closed without merging**
